### ISSUE TITLE
打破0 issue

### ISSUE THREAD

**Issue by Brightest08** [pengpan/91160#1]
https://github.com/pengpan/91160/blob/master/main.py#L181  y_state这个字段网站去除了，会一直刷不到票

**Comment by pengpan** [comment]
没有去除呀，我刚试了都能正常刷票，要看下具体是哪个医院哪个科室可能接口会返回不同。

我这儿试的是深圳北大皮肤科：
[https://www.91160.com/dep/getschmast/uid-21/depid-556/date-2019-10-12/p-0.html](https://www.91160.com/dep/getschmast/uid-21/depid-556/date-2019-10-12/p-0.html)

**Comment by Brightest08** [comment]
嗯，uid应该每个医院都是不一样

**Comment by pengpan** [comment]
已修复好了，可以再试下

**Comment by Brightest08** [comment]
看了下代码存在两处调用login，测试登陆一次后再次登陆会抛异常，就不会执行到get_ticket

**Comment by pengpan** [comment]
已修复。

**Comment by Brightest08** [comment]
请问可以在未放号前获取到schedule_id吗？发现在刷到票之后访问这个页面提交订单https://www.91160.com/guahao/ystep1/uid-{}/depid-{}/schid-{}.html需要三秒时间，可能在这个时间内票就被刷走了(现在的情况也是这样)，想着如果能提前获取到需要post的数据，到点就直接提交订单

**Comment by pengpan** [comment]
`schedule_id`要在放号之后才能拿到，我已经优化了提交订单的程序逻辑，会比之前块了。`https://www.91160.com/guahao/ystep1/uid-{}/depid-{}/schid-{}.html`这个页面不加载无法获取`sch_data`等参数，网速好点应该是不要3s的。
