### ISSUE TITLE
城市ID

### ISSUE THREAD

**Issue by Bruce-Fengxinzi** [pengpan/91160#15]
想要添加其它城市，对应的ID在哪里找到呢？

**Comment by Bruce-Fengxinzi** [comment]
获取的城市和医院很有限，是什么原因？合肥那么多医院但是只显示了十来个，还不是合肥的

**Comment by Bruce-Fengxinzi** [comment]
说是预约成功，查收短信，但是没有收到过短信，打电话问医院，也说没挂上

**Comment by pengpan** [comment]
城市数据：https://github.com/pengpan/91160/blob/master/cities.json

**Comment by jhl27** [comment]
> 说是预约成功，查收短信，但是没有收到过短信，打电话问医院，也说没挂上

同合肥，你成功了吗

**Comment by pengpan** [comment]
已修复https://github.com/pengpan/91160/issues/19#issuecomment-1079572693
