### ISSUE TITLE
城市数据：https://github.com/pengpan/91160/blob/master/cities.json

### ISSUE THREAD

**Issue by Bruce-Fengxinzi** [pengpan/91160#16]
城市数据：https://github.com/pengpan/91160/blob/master/cities.json

_Originally posted by @pengpan in https://github.com/pengpan/91160/issues/15#issuecomment-962570979_

感谢分享！试着挂了个号，提示挂号成功，但是我并没有收到短信，也和医院核实了，确实没有挂上，这是哪里操作不对？

**Comment by S-HongJie** [comment]
同遇到这个

**Comment by pengpan** [comment]
已修复https://github.com/pengpan/91160/issues/19#issuecomment-1079572693
