### ISSUE TITLE
请教一下接口链接是怎么找到的？

### ISSUE THREAD

**Issue by toymil** [pengpan/91160#4]
如 `https://www.91160.com/dep/getschmast/uid-{}/depid-{}/date-{}/p-0.html`，是怎么找到的？
出于性能考量，我想仅获取特定医生的可预约信息（如页面 `https://www.91160.com/doctors/index/unit_id-{}/dep_id-{}/docid-{}.html`）。寻找接口链接应该从哪下手呢？

**Comment by toymil** [comment]
嗯……在 Chrome DevTools 里看到 `https://www.91160.com/dep/getschmast/uid-{}/depid-{}/date-{}/p-0.html` 了，但是在医生页面没有发现类似的东西。

**Comment by toymil** [comment]
发现没有什么特别的必要，从科室数据里获取没什么问题。

**Comment by pengpan** [comment]
这个是单独的接口，刷这个有次数限制

**Comment by pengpan** [comment]
如有兴趣，欢迎大家pull request，最近很忙

**Comment by toymil** [comment]
@pengpan 👌，目前还在看着你的代码尝试。
有一个问题，那个 `PUBLIC_KEY` 是哪来的？

**Comment by toymil** [comment]
> 
> 
> @pengpan 👌，目前还在看着你的代码尝试。
> 有一个问题，那个 `PUBLIC_KEY` 是哪来的？

翻到了，在登陆页面加载的资源文件里……

**Comment by pengpan** [comment]
对的。全部的接口都是抓包获取，有些需要解析网页

**Comment by toymil** [comment]
![Snipaste_2020-08-04_15-05-14](https://user-images.githubusercontent.com/13289283/89263658-3a375580-d664-11ea-856f-5ea586740fa2.png)

从你的代码弄明白了挂号的流程，又自己测试修改了一下发包内容，写了个简单的脚本抢特定「医院-科室-医生-时段」的号。

然后今天实操测试一次过了 🙏，十分感谢。我可能找时间完善一下代码给你发 pr。

**Comment by Kaso001** [comment]
> 



> ![Snipaste_2020-08-04_15-05-14](https://user-images.githubusercontent.com/13289283/89263658-3a375580-d664-11ea-856f-5ea586740fa2.png)
> 
> 从你的代码弄明白了挂号的流程，又自己测试修改了一下发包内容，写了个简单的脚本抢特定「医院-科室-医生-时段」的号。
> 
> 然后今天实操测试一次过了 🙏，十分感谢。我可能找时间完善一下代码给你发 pr。

请问能发我参考一下吗
